version: "3.8"
services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD-password}
      - POSTGRES_DB=${DATABASE_NAME-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    environment:
      - DATABASE_NAME=${DATABASE_NAME-postgres}
      - DATABASE_HOST=${DATABASE_HOST-db}
      - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-password}

    build:
      context: .
      dockerfile: Dockerfile.production
    image: synthez/devops-for-programmers-project-74
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db

volumes:
  db-data:
