version: "3.8"

services:
  caddy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app:/srv
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: synthez/devops-for-programmers-project-74
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm start'
    depends_on:
      - db
