version: "3.9"

services:
  caddy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app:/srv

  app:
    extends:
      file: docker-compose.yml
      service: app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm start'
    depends_on:
      - caddy
      - db
