name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: synthez/devops-for-programmers-project-74
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: make ci

      - name: Build App
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}
